name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted the person'
  fun:
    description: 'Get the String'
runs:
  using: 'composite'
  steps:
    - name: Step 1
      run: echo "Hello World"
      shell: bash
    - name: Step 2
      run: echo "Goodbye"
      shell: bash
    - name: Step 2
      run: pwd
      shell: bash
    - name: Step 2
      run: |
        chmod +x ${{ github.action_path }}/script.sh
        ${{ github.action_path }}/./script.sh
      shell: bash
