name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted the person'
  fun:
    description: 'Get the String'
runs:
  using: 'composite'
  steps:
    - name: Step 1
      run: echo "Hello World"
      shell: bash
    - name: Step 2
      run: echo "Goodbye"
      shell: bash

    - name: Step 3
      run: pwd
      shell: bash

    - name: Step 3 using bash script
      run: |
        chmod +x ${{ github.action_path }}/script.sh
        ${{ github.action_path }}/./script.sh
      shell: bash

    - name: Step 4 using python script
      run: |
        chmod +x ${{ github.action_path }}/dist/script.py
        python ${{ github.action_path }}/dist/script.py
      shell: bash
    
    - name: Step 5 using javascript
      run: |
        chmod +x ${{ github.action_path }}/dist/index.js
        node ${{ github.action_path }}/dist/index.js "${{ inputs.who-to-greet }}"
        echo ${{GITHUB_OUTPUT}}
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Check the inputs from work flow
      run: |
        echo "Input value: ${{ inputs.who-to-greet }}"
      shell: bash
    
    - name: Setting outputs to work flow
      run: |
        echo "time='Timesksdjk111'" >> $GITHUB_OUTPUT
        echo "fun='Hello, World!'" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash
    
    - name: Debug - Show GITHUB_OUTPUT content
      run: cat $GITHUB_OUTPUT
      shell: bash
    
