name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted the person'
  fun:
    description: 'Get the String'
runs:
  using: 'composite'
  steps:
    - name: List root directory
      run: ls -la
      shell: bash

    - name: List dist directory
      run: ls -la dist
      shell: bash
      
    - name: Run Node.js script
      run: node dist/index.js
      shell: bash
